name: alfresco-sync-service
version: 2.0.0-RC2
appVersion: 3.2.0
description: Alfresco Syncservice
keywords:
- syncservice
- alfresco
- application
# home:
# sources:
#   -
maintainers:
- name: Alfresco Apps Repo Team
engine: gotpl
